CC = gcc
CFLAGS = -Wall -Wextra -O2

all: update_slot_manager

update_slot_manager: update_slot_manager.c
	$(CC) $(CFLAGS) update_slot_manager.c -o update_slot_manager

clean:
	rm -f update_slot_manager
