CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2

all: supervisory_control_state_machine

supervisory_control_state_machine: supervisory_control_state_machine.cpp
	$(CXX) $(CXXFLAGS) supervisory_control_state_machine.cpp -o supervisory_control_state_machine

clean:
	rm -f supervisory_control_state_machine
