CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2

all: privacy_gateway_policy

privacy_gateway_policy: privacy_gateway_policy.cpp
	$(CXX) $(CXXFLAGS) privacy_gateway_policy.cpp -o privacy_gateway_policy

clean:
	rm -f privacy_gateway_policy
