CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2

all: edge_runtime_state_machine

edge_runtime_state_machine: edge_runtime_state_machine.cpp
	$(CXX) $(CXXFLAGS) edge_runtime_state_machine.cpp -o edge_runtime_state_machine

clean:
	rm -f edge_runtime_state_machine
