CREATE TABLE IF NOT EXISTS device_inventory (
    device_id TEXT PRIMARY KEY,
    site_id TEXT NOT NULL,
    gateway_id TEXT NOT NULL,
    device_class TEXT NOT NULL,
    sensor_family TEXT NOT NULL,
    connectivity_state TEXT NOT NULL,
    trust_state TEXT NOT NULL,
    lifecycle_state TEXT NOT NULL,
    active_firmware TEXT NOT NULL,
    approved_firmware TEXT NOT NULL,
    active_config TEXT NOT NULL,
    approved_config TEXT NOT NULL,
    active_schema TEXT NOT NULL,
    approved_schema TEXT NOT NULL,
    battery_percent REAL NOT NULL,
    heartbeat_age_seconds REAL NOT NULL,
    credential_state TEXT NOT NULL,
    calibration_version TEXT NOT NULL,
    owner TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS gateway_state (
    gateway_id TEXT PRIMARY KEY,
    site_id TEXT NOT NULL,
    connectivity_state TEXT NOT NULL,
    trust_state TEXT NOT NULL,
    active_rule_version TEXT NOT NULL,
    approved_rule_version TEXT NOT NULL,
    child_device_count INTEGER NOT NULL,
    child_devices_reporting INTEGER NOT NULL,
    buffer_depth INTEGER NOT NULL,
    buffer_capacity INTEGER NOT NULL,
    mean_upload_latency_seconds REAL NOT NULL,
    firmware_version TEXT NOT NULL,
    approved_firmware TEXT NOT NULL,
    local_authority_state TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS telemetry_records (
    event_id TEXT PRIMARY KEY,
    device_id TEXT NOT NULL,
    site_id TEXT NOT NULL,
    gateway_id TEXT NOT NULL,
    sensor_family TEXT NOT NULL,
    event_time TEXT NOT NULL,
    upload_time TEXT NOT NULL,
    ingestion_time TEXT NOT NULL,
    processing_time TEXT NOT NULL,
    value REAL NOT NULL,
    unit TEXT NOT NULL,
    quality_state TEXT NOT NULL,
    trust_state TEXT NOT NULL,
    sequence_number INTEGER NOT NULL,
    replay_batch_id TEXT,
    idempotency_key TEXT NOT NULL,
    duplicate_detected BOOLEAN NOT NULL,
    drop_reason TEXT,
    active_firmware TEXT NOT NULL,
    approved_firmware TEXT NOT NULL,
    active_config TEXT NOT NULL,
    approved_config TEXT NOT NULL,
    active_schema TEXT NOT NULL,
    approved_schema TEXT NOT NULL,
    command_related BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS command_log (
    command_id TEXT PRIMARY KEY,
    issuer TEXT NOT NULL,
    target_device_id TEXT,
    target_gateway_id TEXT,
    command_type TEXT NOT NULL,
    requested_time TEXT NOT NULL,
    ack_time TEXT,
    trust_state TEXT NOT NULL,
    freshness_required_seconds REAL NOT NULL,
    observed_freshness_seconds REAL NOT NULL,
    local_safety_check BOOLEAN NOT NULL,
    authorized BOOLEAN NOT NULL,
    acknowledged BOOLEAN NOT NULL,
    rollback_ready BOOLEAN NOT NULL,
    command_result TEXT NOT NULL
);
