CXX = g++
CXXFLAGS = -std=c++17 -Wall -Wextra -O2

all: autonomy_state_machine

autonomy_state_machine: autonomy_state_machine.cpp
	$(CXX) $(CXXFLAGS) autonomy_state_machine.cpp -o autonomy_state_machine

clean:
	rm -f autonomy_state_machine
